version: '3.8'

services:
  service_csharp:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    restart: always
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - 3001
    ports:
      - 3001:3001
    command: sh -c 'dotnet restore && dotnet run'